name: Build and Release

on:
  push:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Action / Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Action / Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Action / Install Dependencies
        run: yarn install

      - name: Action / Build
        run: yarn run prod

      - name: Action / Release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          push_options: '--force'
          commit_message: 'I have released a new version!'
          file_pattern: 'dist/sak32009-get-dlc-info-from-steamdb.user.js'
